import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/providers/AppProvider";
import { cn } from "@/libs/utils";

const montserrat = Montserrat({
	variable: "--font-mont",
	subsets: ["latin"],
});

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth" suppressHydrationWarning>
			<body
				className={cn(
					montserrat.variable,
					poppins.variable,
					"antialiased font-mont"
				)}
			>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	);
}
